systems:
  - ident: 0
    initial_state: [0., 0., 0.]
    dynamics:
      state: x y th
      input: v omega
      dxdt: [v*cos(th), v*sin(th), omega]
    visual: 
      type: simple_car

  - ident: 1
    initial_state: [0.5, 0., 0.1]
    dynamics:
      state: x y th
      input: v omega
      dxdt: [v*cos(th), v*sin(th), omega]
    visual: 
      type: simple_car
